// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Entity struct {
	ID          int64
	CanonicalID string
}

type Heartbeat struct {
	ID         int64
	EntityID   int64
	Ts         time.Time
	Successful bool
	Error      sql.NullString
}

type Metric struct {
	ID       int64
	EntityID int64
	Ts       time.Time
	Name     string
	Type     string
	Value    float64
	Labels   json.RawMessage
}
