// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Entity struct {
	ID          int64
	CanonicalID string
}

type Heartbeat struct {
	ObsID      int64
	Successful bool
	Error      sql.NullString
}

type Observation struct {
	ID       int64
	EntityID sql.NullInt64
	Ts       time.Time
	Kind     string
}
