// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const getAllEntityIDs = `-- name: GetAllEntityIDs :many
select id, canonical_id from entities
`

func (q *Queries) GetAllEntityIDs(ctx context.Context) ([]Entity, error) {
	rows, err := q.db.QueryContext(ctx, getAllEntityIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entity
	for rows.Next() {
		var i Entity
		if err := rows.Scan(&i.ID, &i.CanonicalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
